etc/modprobe.d/nvidia.conf

Adding a some of important parameters for driver modules.
I'll make a few remarks:
`NVreg_UsePageAttributeTable=1` (Default 0) -  Improves CPU performance on laptops (See https://bbs.archlinux.org/viewtopic.php?id=242007).
`NVreg_EnablePCIeGen3=1` (Default 0) - Enables full PCIe 3.0 support for graphics cards. The following is written in nv-reg.h about this parameter:
>  Due to interoperability problems seen with Kepler PCIe Gen3 capable GPUs
>  when configured on SandyBridge E desktop platforms, NVIDIA feels that
>  delivering a reliable, high-quality experience is not currently possible in
>  PCIe Gen3 mode on all PCIe Gen3 platforms. Therefore, Quadro, Tesla and
>  NVS Kepler products operate in PCIe Gen2 mode by default. You may use this
>  option to enable PCIe Gen3 support.
However, …

Add some parameters for the NVIDIA driver module

---

etc/modprobe.d/nvidia.conf

We need this to enable NVIDIA PRIME Sync on laptops (a guaranteed way to fix tearing). It also requires a special hook to update initramfs every time the driver is updated, so it's Draft for now.

Enable NVIDIA DRM KMS by default

---

etc/bluetooth/main.conf

- Enables D-Bus experimental interfaces
- Enables kernel experimental features
- Enables Multi Profile Specification support. This allows to specify if # system supports only Multiple Profiles Single Device (MPSD) configuration # or both Multiple Profiles Single Device (MPSD) and Multiple Profiles Multiple
I made these changes based on: https://wiki.archlinux.org/title/bluetooth_headset#Battery_level_reporting
Effect: Headest report battery level.

bluetooth-tweaks

---

etc/udev/rules.d/30-zram.rules

Since we already have `CONFIG_ZRAM_MULTI_COMP` enabled in our kernel, I thought that we could provide by default recompressions to ZRAM.  Double compression will save more memory for those pages that cannot be compressed with Zstd (since we use it by default), in this PR I decided to set double compression only for idle pages, since huge pages were reverted with the commit https://github.com/CachyOS/CachyOS-Settings/commit/48f40a564135a80ff23463d66e129856bbdcfe38. The re-compression algorithm can be changed in the future, for now I stopped at LZ4.
This was done as a udev rule as a temporary solution, since it is better to have this feature directly in the zram-generator, but until it is absent we will limit ourselves to this rule.
It also works only for kernel versions 6.2 and higher, for …

udev: Add ZRAM recompression by default

---

etc/modprobe.d/nvidia.conf

It helps laptop configurations and almost does not interfere with systems that do not support it (this will simply cause the following display of status in `/proc/driver/nvidia/gpus/0000:01:00.0/power` - `Runtime D3 status: Not supported`).
This is also already included in the Negativo17 driver for Fedora:
https://github.com/negativo17/nvidia-kmod-common/blob/master/nvidia.conf

nvidia: Enable dynamic power management by default

---

etc/udev/rules.d/71-nvidia.rules
etc/udev/rules.d/80-nvidia-pm.rules

Basically just a backport of rules from Ubuntu, but this should fix us from being tied to mhwd-gpu. Should have no effect on non-NVIDIA configurations, including nouveau.
P. S. I'm not sure if I should merge them with the 80-nvidia-pm.rules, so I made a separate file.

Add rules to prevent of lacks nvidia modules

---

usr/bin/pci-latency

Just worried about possible errors because of grep

pci-latency: Replace grep with the lspci device filter by class

---

etc/sysctl.d/99-cachyos-settings.conf

Okay, let me try to explain why. The point is that since kernel version 5.8 the behavior of the kernel with respect to `vm.swappiness` has changed [1][2]. First, `vm.swappienss` no longer controls or sets a threshold for when swap starts to be used.  Now the parameter vm.swappiness is a kind of "scales", depending on which way it is tilted, the kernel will prefer to free a certain type of pages [3][4]. A value between 0 and 200 means that the kernel will be the first to dump to disk, page cache or anonymous pages to swap if possible. Low values mean that the kernel will first try to flush the page cache, and only then anonymous pages to the swap. High values mean swap first. A value of 100 means balance, i.e. the kernel will equally try to flush anonymous pages and page cache to disk at …

sysctl: Increase swappiness to 100

---

etc/sysctl.d/99-cachyos-settings.conf

The settings for the network can be reviewed and returned. But for now, they will be removed.
Also note what the Arch Wiki says about these settings:
> This section seems motivated by the Cloudflare blog post, but Red Hat's tuned profile suggests even smaller values and claims "this seems only necessary at 40Gb speeds". Hence, these settings do not seem useful for commodity hardware.
https://wiki.archlinux.org/title/Sysctl#Increase_the_memory_dedicated_to_the_network_interfaces
https://github.com/redhat-performance/tuned/blob/master/profiles/network-throughput/tuned.conf#L10
I also have some doubts about the current values of dirty_ratio.

Clean up sysctl

---

etc/modprobe.d/amdgpu.conf

We have already received a lot of issues from users about Vulkan not working on old AMD cards due to lack of amdgpu driver. I think it makes sense to force its use by default, since users will want to do it anyway and our kernel supports this feature. 
Refs:
https://wiki.archlinux.org/title/AMDGPU#Enable_Southern_Islands_(SI)_and_Sea_Islands_(CIK)_support
https://github.com/ValveSoftware/Proton/wiki/For-AMD-users-having-issues-with-non-OpenGL-games
https://gitlab.freedesktop.org/drm/amd/-/issues/1776

modprobe.d: Force using of amdgpu driver for older graphics cards by default

---

etc/udev/rules.d/30-zram.rules

Since we ship zram by default via zram-generator, I think we should do some extra tuning through new ``zramtune`` service.
This service performs:
- Set the ``vm.swappiness`` value to 150. We need to push anonymous pages out more, once they are located in ZRAM.
- Setting idle pages re-compression (we used to have this in an udev rule, but it didn't seem to work properly).
- Set ``vm.watermark_scaling_factor`` parameter as recommended here:
https://www.reddit.com/r/linux_gaming/comments/vla9gd/comment/ie1cnrh/
The list of changes is not too long, but it creates a convenient opportunity to define ZRAM-specific settings later on.

udev: Tune ZRAM rules for better performance

---

etc/tmpfiles.d/thp.conf

This should improve the performance of applications that use the tcmalloc memory allocator, which is used by Chromium/Electron and Valve's native games, among others.
Ref: https://github.com/google/tcmalloc/blob/master/docs/tuning.md#system-level-optimizations

Enable defer+madvise defragmention for THP by default

---

etc/modprobe.d/nvidia.conf

This adds the new nvidia option "fbdev=1" as default for the nvidia module.
This option is required for some nvidia cards to have a proper wayland experience. [1}
On top this provides a framebuffer, which is scaled to the default monitor resolution.
1. https://forums.developer.nvidia.com/t/kde-wayland-doesnt-work-on-the-545-drivers/269794/2

nvidia: Add fbdev=1 as default

---

etc/udev/rules.d/60-ioschedulers.rules

I have tested kyber for the nvme in various workloads and it does improve the repressives of the desktop under heavy IO scenarios a lot compared to "none". 
Throughput appears to be lower for around 3% in my testings (tested with kdiskmark).
Also see following:
https://github.com/pop-os/default-settings/pull/149
Fixes: https://github.com/CachyOS/CachyOS-Settings/issues/34

io-scheduler: Use kyber for nvme's and ssd's

---

etc/udev/rules.d/71-nvidia.rules

It seems to be causing some boot/shutdown issues. Also not sure if they were useful in the current setup

udev: Remove force loading of nvidia modules

---

etc/udev/rules.d/30-zram.rules

This reduces CPU overhead while saving memory in the case of pages that could not be compressed by the primary algorithm. This also gets rid of the `CONFIG_ZRAM_MEMORY_TRACKING` dependency for the kernel.
Thanks @firelzrd for the hint.

udev/zram: Try to re-compress only uncompressed pages

---

etc/systemd/zram-generator.conf

It is important to be aware that the size of ZRAM block device does not reflect the actual size of compressed pages it contains. The ZRAM size is the total number of pages that can be placed in swap as if it were on disk, but if you look through `zramctl` in the `COMPR` column, you can see that actual size has shrunk by a factor of about three (as the kernel developers claim and it's close to the truth). So the larger ZRAM size actually allows for more capacity for compressed pages as well. We also need this because of the high ``vm.swappiness`` value, which forces kernel to push more pages into ZRAM.
Also read on arch wiki about that: https://wiki.archlinux.org/title/Zram#Usage_as_swap

zram-generator: Make ZRAM size equal to RAM

---

etc/udev/rules.d/60-ioschedulers.rules

BFQ is prone to regressive behavior on SSD/SD cards. Actually, for the SATA SSDs I'm more inclined to use none as well as NVMe, but I'm not sure about that yet.

udev/ioschedulers: Use mq-deadline for SSD/SD cards

---

etc/udev/rules.d/30-zram.rules

This causes an unnecessarily large increase in RAM consumption.

udev/zram: Drop tuning for watermark values 

---

etc/debuginfod/cachyos.urls

Currently debuginfod uses as default the archlinux debuginfod URL, which makes issues when used together with CachyOS. The Archlinux URL is still required, since we dont ship all packages yet.
Fixes: https://github.com/CachyOS/CachyOS-Settings/issues/57

Add CachyOS URL to debuginfod

---

usr/bin/cachy-chroot

Initial release of cachy-chroot script. This script simplifies the process of chrooting by prompt-based selection of the block devices and the mount points. It also handles BTRFS subvolumes automatically.

feat: add cachy-chroot script

---

usr/bin/ksmctl
usr/lib/systemd/system/gdm.service.d/10-ksm.conf
usr/lib/systemd/system/getty@.service.d/10-ksm.conf
usr/lib/systemd/system/lightdm.service.d/10-ksm.conf
usr/lib/systemd/system/ly.service.d/10-ksm.conf
usr/lib/systemd/system/sddm.service.d/10-ksm.conf
usr/lib/systemd/system/user@.service.d/10-ksm.conf
usr/lib/tmpfiles.d/ksm.conf

systemd allows to use the same mechanism (kernel API) as uksmd using the `MemoryKSM=yes` service option. The idea is that we take the processes that are parent to most user processes like display managers (SDDM/GDM/LightMD/Ly/etc) or getty in case we don't have a display manager, and enable `MemoryKSM=yes` for them, so that all child processes inherit the PR_SET_MEMORY_MERGE attribute, which gives ksmd a hint that the pages of this process can be merged. Unlike uksmd it allows us to: 
1) Don't waste a lot of unnecessary CPU time for tracking down new processes.
2) No need for additional kernel patches that will probably never be accepted in upstream.
3) Avoid depending on extra services/packages which may be undesirable for some users (see …

Replace uksmd with built-in KSM support in systemd 

---

usr/bin/ksmstats

A simple conversion of uksmdstats to ksmstats.
```
lucjan at cachyos ~ 12:10:22    
❯ ksmstats
======================================================
ksmstats for CachyOS
======================================================
Full scans               13       
Interval                 20 ms    
Max page sharing ratio   256      
Pages to scan            100      
Pages over ratio         3        
Duplicated pages         58       
Use zero pages           0        
Sharing/shared ratio     9.81861  
Unshared/sharing ratio   5.74012  
Pages sharing            123.27   MiB
Pages shared             12.5547  MiB
Pages unshared           707.582  MiB
General profit           96.2643  MiB
```

Add ksmstats for CachyOS

---

usr/bin/game-performance

CachyOS does not use Gamemode as default, which makes it a bit harder to switch to the performance governor.
Lets provide a script, which simply utilizes power-profiles-daemon to switch to the performance mode.
User can add to the Game Launch Options:
`game-performance %command% `
todo:
Make it maybe reset, when game does stop

Add helper script to set powerprofiles to performance

---

usr/bin/cachy-chroot

hides .snapshots btrfs subvolumes from the subvolume list, to enable listing and selecting .snapshots subvolumes, the user can pass the --show-btrfs-dot-snapshots flag to cachy-chroot

feat: hide .snapshots btrfs subvolumes by default

---

usr/bin/sbctl-batch-sign

sbctl-batch-sign is a helper script designed to make it easier for users to sign files needed for secure boot support. The obvious case in which this script helps a lot is when dual booting Windows as there are a lot of files by Windows that needs to be signed in EFI.
Windows files in EFI that needs to be signed:
To be merged with https://github.com/CachyOS/wiki/pull/42

feat: add sbctl-sign-batch for secure boot

---

usr/lib/sysctl.d/99-cachyos-settings.conf
usr/lib/tmpfiles.d/coredump.conf

And also configure cleanup for dumps created more than 3 days ago to save disk space (systemd default is 2 weeks).

sysctl.d: Leave core dumps creating enabled by default

---

usr/lib/NetworkManager/conf.d/dns.conf

implements config changes required for https://github.com/CachyOS/CachyOS-Settings/issues/79

networkmanager: use systemd-resolved as default dns resolver

---

usr/bin/sbctl-batch-sign

When using GRUB or rEFInd, sometimes the kernel images that live in `/boot` does not get detected by `sbctl` because `sbctl` is only scanning for the EFI partition `/boot/efi`. This may be a limitation in sbctl itself or something with how we partition our installs and needs to be investigated further.

sbctl-batch-sign: Add workaround for /boot and /boot/efi partitioned systems

---

usr/lib/environment.d/gnome.conf

Related with many upstream issues:
https://gitlab.gnome.org/GNOME/mutter/-/issues/3450
https://gitlab.gnome.org/GNOME/mutter/-/issues/3358
https://bbs.archlinux.org/viewtopic.php?id=289584
https://discourse.gnome.org/t/gnome-shell-getting-killed-with-no-coredump-artifacting-with-workaround-fix/22828

Add workaround for GNOME Wayland crashes

---

usr/lib/udev/rules.d/50-sata.rules

For some removable devices link_power_management_policy cannot be changed, causing some annoying errors in logs.

udev/sata: Check for presence of power management policy attribute

---

usr/bin/game-performance

Besides, specifying `-p` seems redundant. This is the default performance.

game-performance: Fix incorrect argument passing

---

usr/lib/modprobe.d/nvidia.conf

Currently, NVIDIA's GSP firmware can be a bit problematic on some systems, causing frequent stutters and performance issues in general. I think it's best
that we disable this by default in our settings to ensure a more convenient user experience. "Convenient" because:
1. We currently install the open kernel modules as the default for all supported GPUs. We can refer to these groups of users with supported GPUs with 'A'.
2. 'A' will most likely switch to the proprietary kernel modules and will want to disable GSP if experiencing performance issues
3. This sort of provides an "auto switcher" of sorts for the GSP firmware, since it can't be disabled with the open modules, i.e. always enabled, and because it's disabled when installing the closed kernel modules.
4. Because of [3], this line in …

[RFC] modprobe.d/nvidia: Disable GSP firmware by default

---

usr/lib/tmpfiles.d/thp-shrinker.conf

Using the always mode (which is default in Archlinux and CachyOS) provides a quite big performance improvement compared to madvise, but this comes with an increased memory usage.
Recently META has contributed the THP Shrinker, which allows to split pages which are underutilized. This can reduce the used memory usage, while providing mostly the same performance improvement.
409 is the provide value by META and we might want to search for more suited values on the desktop. Also, we should do some benchmarks (cachyos-benchmarker) to see if there is a massive difference between 509 and 411.
https://lore.kernel.org/lkml/20240830100438.3623486-1-usamaarif642@gmail.com/

tmpfiles.d: Add thp-shrinker config to reduce memory usage

---

usr/lib/sysctl.d/99-cachyos-settings.conf

The comments here makes this tunable a bit misleading. Runtime is actually the allocated time from the total period time that is given for RT tasks. A value of -1 indicates that the runtime is equal to the total period, i.e. no limit from total period, and no extra time for non-RT tasks. Reading the documentation[1], it seems that the kernel defaults are favorable compared to what we have right now.
[1] https://github.com/CachyOS/linux/blob/6.12/fixes/Documentation/scheduler/sched-rt-group.rst#21-system-wide-settings

sysctl.d/cachyos-settings: Remove kernel.sched_rt_runtime_us

---

usr/lib/sysctl.d/99-cachyos-settings.conf

Currently there seems to be a bit of a redundancy in the settings set here, so I'd like to clean it up a bit. There are also some removals/tweaks to settings that don't make quite sense to me (based on my limited knowledge), so I've opted to removed them in the PR, but I am very open for discussion.

Various sysctl cleanups

---

usr/lib/sysctl.d/99-cachyos-settings.conf

There has been reports of slow connection speeds when using CachyOS that are not present when using other distributions. This has been bisected to our sysctl tunables. The other 2 commits serve as a cleanup to:
1. A potential security hazard
2. Keeping saner defaults

sysctl: Network Tunables Cleanup

---

usr/lib/sysctl.d/99-cachyos-settings.conf

The point is that the greater difference between `vm.dirty_background_bytes` and `vm.dirty_bytes`, the more we avoid possibility of trotting and short I/O pauses for actively writing processes called by the kernel to prevent dirty pages overflows if pdflush doesn't have time to write changes [1]. This is also better from the point of view of data safety, so that it does not stagnate in RAM for too long, as otherwise it risks losing it in case of a power failure or system hang. It is also there now, but at least guarantee that the data loss is not too large.
[1] - https://lwn.net/Articles/456904/

sysctl: Reduce vm.dirty_background_bytes value

---

usr/bin/game-performance

This is what gamemode does by default and is requested in https://github.com/CachyOS/CachyOS-Settings/issues/119.
Closes: https://github.com/CachyOS/CachyOS-Settings/issues/119

game-performance: Disable screensaver during running

---

usr/lib/udev/rules.d/80-ntfs3-by-default.rules

`ntfs` is classified as an unknown filesystem according to Linux and users can't directly mount such partitions directly. Instead, users must explicitly specify the filesystem type, e.g. `mount -t ntfs3 /dev/sdxY /mnt` to mount the partition successfully.
As a QoL change, adding this udev rule can use the `ntfs3` kernel driver by default without explicitly specifying it. Note that this can apparently confuse 3rd party tools and isn't recommended by the Arch wiki. (I'm not entirely sure what this "confusion" is. I guess we would need to have some NTFS users test this.)
Link: https://wiki.archlinux.org/title/NTFS#unknown_filesystem_type_'ntfs'

udev: Use ntfs3 as the default driver for ntfs partitions

---

usr/bin/cachyos-bugreport.sh

It is all too common practice to ask about what versions of packages are installed, as this helps to identify packaging issues. To preserve the confidentiality of installed software on the user's system, this PR only exposes information about installed packages from cachyos-v3 or cachyos-v4, which have a limited set of packages but are useful for debugging issues like NVIDIA and mesa drivers, toolchain, compression libraries, etc.

cachyos-bugreport: Include list of installed packages from v3 or v4 repo

---

usr/bin/sbctl-batch-sign

Unfortunately, the prior version of the script caused massive issues for upstream[1][2] due to being poorly written and without any safeguards (mostly due to *a lot* of assumptions). The script is now hopefully better implemented due better protect against these issues by:
1. Actually filtering for unsigned files only this time; see  6d49e37ab94871cce421f9f508bce91f6027664f
2. Ignore ESP files from Microsoft and known files that are not proper PE executables; see 070ff71c21ec519aa97f76a7bc55506e3b9e9680 and eb4baca3911bc0fcac81e89e36ad6f8831e14d28
3. Protect against weird edgecases which may occur from the script due to empty output from either `sbctl` or `find`, and hypothetical filenames with spaces.
[1] https://github.com/Foxboron/sbctl/issues/414
[2] …

fix: sbctl-batch-sign: Better handling of batch file signing by blacklisting known improper PE/COFF executables

---

usr/lib/sysctl.d/99-cachyos-settings.conf

Historically, negotiating ECN for outgoing connections has caused problems. systemd has tried to enable it in the past [1], but it was quickly reverted due to said problems [2]. Now, we got reports of performance issues with webservers and VMs [3]. Let's stick to the defaults with this one
[1] https://github.com/systemd/systemd/commit/919472741dba6ad0a3f6c2b76d390a02d0e2fdc3
[2] https://github.com/systemd/systemd/pull/9880
[3] https://discuss.cachyos.org/t/strange-performance-using-ansible-and-maybe-other-programs/6079

sysctl.d: Do not set net.ipv4.tcp_ecn

---

usr/lib/udev/rules.d/99-ntsync.rules

Upstream will add a patch, which makes the module automatically the correct permissions.
This has been applied to the RC (6.14.rc3) and 6.13.3 kernel. As soon they are available we can merge this.

udev: Drop ntsync rule, handled now directly by the kernel

---

usr/bin/dlss-swapper
usr/bin/dlss-swapper-dll

This adds script, which can be used in Steam as launch options.
The `dlss-swapper` does set the dlss preset to the latest available, and also update the dlls via ngx-updater.
NGX Updater is currently not working reliable at all games, and can result into crashes.
The `dlss-swapper-dll` script, only sets the preset to latest. This can be used by users, when they manually switch the dll's in the games directory.
Till ngx updater is working reliable, we likely want to keep the second script too, to make it easier for the user.
Im not sure, how we should call the scripts, so im open for suggestions.
Thanks to @ferrreo for bringing this script up :)

dlss: add script to switch to latest dlss preset

---

usr/lib/modprobe.d/nvidia.conf

NVIDIA has recently fixed the GSP Firmware stutters and also performance in some scenarios.
Since this is now not anymore a major issue, we should enable the GSP firmware again and following nvidia's defaults.
Users, which might still run into issues can change it manually back.

nvidia.conf: Enable GSP Firmware again

---

usr/lib/udev/rules.d/80-ntfs3-by-default.rules

There has been multiple reports that the ntfs3 kernel driver causes data loss. Revert this until ntfs3 is at
a useable state again. It's better that mounting partitions as `ntfs` doesn't work by default rather than
it mounting but causing irreparable damage in the end.

Revert "udev: Use ntfs3 as the default driver for ntfs partitions"

---

usr/bin/sbctl-batch-sign

Exporting this variable effectively gives us the same functionality as was given with the find workaround,
with the extra works that the listed files are actually ESP files, as validated by sbctl.
This removes the variable olympics we were doing as to not pass bogus lists to sbctl when signing.
This workaround is mainly for GRUB installs and old rEFInd installs. systemd-boot installs and new-ish rEFInd
installs (post partition table changes) won't need this workaround, and functionality remains the same there.
Unfortunately, this will break weird installs that have weird paths set as their ESP, e.g. /efi. However,
we were already hardcoding /boot in the find workaround anyway, so I'd like to believe that this won't change
anything. CachyOS only supports installs with /boot as their ESP at …

sbctl-batch-sign: Export ESP_PATH and replace find workaround

---

usr/bin/zink-run

`__EGL_VENDOR_LIBRARY_FILENAMES` defaults to `/usr/share/glvnd/egl_vendor.d/10_nvidia.json` on nvidia so it needs to be updated to use mesa for zink to work when using zink with a native wayland program.
`zink-run eglgears_wayland` does not correctly use zink.
`__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json zink-run eglgears_wayland` does correctly use zink.
X11 is a little weirder though because `MANGOHUD=1 zink-run eglgears_x11` does not initialize mangohud like a vulkan program should, but `zink-run mangohud eglgears_x11` does initialize mangohud and mangohud reports that zink is being used but if zink were being used than `mangohud` in the command shouldn't be needed. `zink-run mangohud eglgears_wayland` mangohud reports `OpenGL` unlike eglgears_x11. Both …

zink-run: Add EGL env for Nvidia compatibility

---

usr/lib/modprobe.d/20-audio-pm.conf
usr/lib/udev/rules.d/20-audio-pm.rules

I received a number of reports, and decided to make a udev rule to prevent such issues with condition that we don't degrade battery life of the devices. 
Needs testing on desktop PCs.

udev: Add rule to prevent audio cracking on some hardware

---

usr/bin/sbctl-batch-sign

We're already checking if the user isn't root before the main body of the script, so there is no need to wrap it again with a check if the user is root

sbctl-batch-sign: Remove unnecessary root check

---

usr/lib/udev/rules.d/20-audio-pm.rules

Somehow, disabling power saving for NVIDIA audio device also prevents the dGPU from going into sleep mode.
See: https://github.com/CachyOS/CachyOS-Settings/pull/147#issuecomment-2952595836

udev: Do not disable powersaving for NVIDIA audio devices

---

usr/lib/tmpfiles.d/optimize-interruptfreq.conf

I've gotten one report from a user who consistently gets hangs until deleting this file. I also doubt it's actually relevant since all mentions of it date back to 2012 and ALSA already has a snd_hrtimer module that probably makes audio processing stuff completely independent from RTC interrupt frequency.
This reverts commit a7b5af383eea9b8ef0d23beaf6f70340a46f236f.

Reapply "tmpfiles.d: Remove interrupt frequency optimization"

---

usr/lib/modprobe.d/nvidia.conf

All NVIDIA module packages in our repository are patched to enable modeset by default, so this is unnecessary, but can also cause issues on older driver versions such as 390.xx.
See: https://github.com/CachyOS/CachyOS-PKGBUILDS/commit/396ecc5a4a11768ff387baffe35824e473bc9b43

modprobe.d/nvidia: Remove modeset parameter

---

etc/security/limits.d/20-audio.conf

This partially reverts 8181bdcb67eaffdb9cb884e4a1fd4c3aed1918fd.
The issue is that all PipeWire threads actually spawns with SCHED_FLAG_RESET_ON_FORK, which is makes ananicy rules in this case pretty useless.
On other side, realtime-privileges limits max nice level to -11, so it's breaks many of ananicy rules, so we can't recommend using it.

Restore unlimited RT priority for audio

---

usr/lib/udev/rules.d/69-hdparm.rules

udev: Only apply hdparm udev rule on ATA devices
